require(['./config',], function () {
    require([
        'partials/permutation-filter',
        'webui-popover',
        'partials/popover-fiter',
        'partials/catalog-filter',
        'partials/product-slider',
        'partials/popover-tooltip',
        'partials/popover-size',
        'partials/scroll-tag',
        'partials/range',
        'partials/hidden-slider',
        'partials/permutation-popular',
        'partials/open-menu-in-popup',
        'partials/ajax',
        'partials/product-preview',
        'partials/basket',
        'partials/pick-slider'
    ]);
});
